package eu.asyroka.msc.persistence;

public enum ProcessStatus {
	NEW,
	PARSING_INPUT,
	INPUT_PARSED,
	GENERATING_PROJECTIONS,
	PROJECTIONS_GENERATED,
	MERGING_PROJECTIONS,
	PROJECTIONS_MERGED,
	PRIORITIZING_PROJECTIONS,
	PROJECTIONS_PRIORITIZED,
	BENCHMARKING,
	FINISHED,
	ERROR
}
